### ISSUE TITLE
invalid pointer

### ISSUE THREAD

**Issue by PAStheLoD** [gunyarakun/gdbruby#3]
Hello!

This project looks very promising, alas I was not able to try it in vivo.

```
pas@stranger:~/local/gdbruby$ /opt/vagrant/embedded/bin/ruby bin/gdbruby.rb 24065 verbose_gdb=1
.... 
R: #67 0x00000000004009d1 in main ()
R: (gdb) 
C: p ruby_current_thread
R: $81 = 54262240
R: (gdb) 
bin/gdbruby.rb:154:in `cmd_get_pointer': Invalid pointer $81 = 54262240 (RuntimeError)
(gdb) 
	from bin/gdbruby.rb:491:in `show_backtrace'
	from bin/gdbruby.rb:368:in `block in trace'
	from bin/gdbruby.rb:123:in `run'
	from bin/gdbruby.rb:365:in `trace'
	from bin/gdbruby.rb:528:in `main'
	from bin/gdbruby.rb:531:in `<main>'
```

[Here](http://pastebin.com/TDLxxksA)'s the full output. (GitHub didn't let me include it.)

Could you help me get gdbruby working?

Thanks!

**Comment by gunyarakun** [comment]
Sorry for late response.
The latest version might solve the problem you faced.

**Comment by PAStheLoD** [comment]
No problem! It was likely a Vagrant core and plugin version mismatch, but figuring out was not easy :)

**Comment by gunyarakun** [comment]
@PAStheLoD Anyway, thanks for your response!
